/******************************************************************************
 *
 * Module: ULTRASONIC SENSOR
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the ATmega32 ULTRASONIC SENSOR driver
 *
 * Author: Misara Ahmed
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"
#include "common_macros.h"
#include "gpio.h"
#include "icu.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define ULTRASONIC_TRIG_PORT       PORTB_ID

#define ULTRASONIC_TRIG_PIN        PIN5_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Function responsible for :
 * -initializing the icu driver.
 * -setup the icu call back function.
 * -Setup the direction for the trigger pin as output pin.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Function responsible for sending the trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * Function responsible for calling the Ultrasonic_Trigger function and starting the icu measurement.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * Function responsible for calculating the high time generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
